# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI/CD

on:
  push:
    paths: 
      - 'client/**'
    branches: [ "main" ]
  pull_request:
    paths: 
      - 'client/**'
    branches: [ "main" ]

defaults:
  run:
    working-directory: client

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
      with:
        path: client
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        path: client
    - name: Makes the client folder the working directory to run npm
      run: cd client
      working-directory: ./client
      
    - name: Does a clean install of dependencies
      run: npm ci
      working-directory: ./client
      
    - name: Runs any tests
      run: npm run test
      working-directory: ./client
      
    - name: Builds out the application
      run: npm run build --if-present
      working-directory: ./client
      
    - name: Deploys and serves application
      run: npm run deploy
      working-directory: ./client
